#! /bin/bash
###
## Author: Selvakumar Esra
# description:  Enables Confluient Platform Kafka service
#
# Simple wrapper to start/stop services as part of
# the Confluent Platform.
#

exitCode=0
name=cp-kafka-service
desc="Confluent Platform Kafka daemon"

# These variables __should__ be imported from a well-defined location.
# For now, we'll set them by some quick searches for the known properties files.
#
THIS_SCRIPT="$(dirname "$(readlink "${BASH_SOURCE[0]}")")"
INIT_HOME=$(dirname $THIS_SCRIPT)
CONF_HOME=$(dirname $INIT_HOME)
CONF_BIN=$CONF_HOME/bin
CONF_ETC=$CONF_HOME/etc/kafka

# PID & LOCK files
PID_DIR=var/run
LOCK_DIR=var/lock/subsys
PIDFILE=$PID_DIR/${name}.pid
[ ! -d $LOCK_DIR ] && LOCK_DIR=var/lock
LOCKFILE=$LOCK_DIR/${name}


CONF_PROPERTIES=${CONF_ETC}/server.properties
CONF_USER=`stat -f '%Su' $CONF_PROPERTIES`
CONF_CLASS='io.confluent.*.SupportedKafka'
PROPERTY_FILE_NAME=`basename $CONF_PROPERTIES`


do_start() {
	echo -n $"Starting $desc ($name) ... "
    nohup $CONF_BIN/kafka-server-start $CONF_PROPERTIES >/dev/null 2>&1 &
    if [ $? -eq 0 ] ; then
        PID=`pgrep -u $CONF_USER -f $CONF_CLASS`
        [ -n "${PID}" ] && echo $PID > $PIDFILE
        exitCode=$?
        echo "done"
    else
        echo "FAILED"
        exit 1
    fi
    [ $exitCode -eq 0 ] && [ -d $LOCK_DIR ] && touch $LOCKFILE
    return $exitCode
}

do_stop() {

    echo -n $"Stopping $desc ($name) ... "
    [ -s $PIDFILE ] && PID=`cat $PIDFILE`
    [ -z "${PID:-}"  ] && $CONF_BIN/kafka-server-stop $CONF_PROPERTIES

    if [ -f $PIDFILE ] ; then
        PID=$(cat $PIDFILE)
    else
        PID=`pgrep -u $CONF_USER -f $CONF_CLASS`
    fi

    [ -n "$PID" ] && kill -9 $PID
    exitCode=$?
    [ $exitCode -eq 0 ] && rm -f $LOCKFILE $PIDFILE
    echo "done"

}

do_restart() {
	do_stop
	sleep 3
	do_start
}


do_status(){
    [ -s $PIDFILE ] && PID=`cat $PIDFILE`
    CURRENT_PID=`pgrep -u $CONF_USER -f $CONF_CLASS`
    if [[ ! -z "$PID" && ! -z "$CURRENT_PID" && "$PID" = "$CURRENT_PID" ]]  ; then
        echo "($name) is running"
	else
		echo "($name) is not running. Restart $name"
	fi
}

do_condrestart() {
	[ -e $LOCK_FILE ] && do_restart || :
	exitCode=$?
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	status)
		do_status
		;;
	qstatus)
		do_qstatus
		;;
	restart)
		do_restart
		;;
	condrestart)
		do_condrestart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|condrestart}"
		exit 1
esac

exit $exitCode



